# Generated by Django 5.2.17 on 2026-09-17 18:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dossier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("question", models.TextField()),
                ("year_from", models.PositiveIntegerField(default=2020)),
                ("limit", models.PositiveSmallIntegerField(default=12)),
                ("status", models.CharField(default="queued", max_length=20)),
                ("stage", models.CharField(default="plan", max_length=20)),
                ("plan", models.JSONField(default=dict)),
                ("papers", models.JSONField(default=list)),
                ("selected", models.JSONField(default=list)),
                ("report", models.JSONField(default=dict)),
                ("report_selected", models.JSONField(default=list)),
                ("versions", models.JSONField(default=list)),
                ("events", models.JSONField(default=list)),
                ("error", models.TextField(blank=True)),
                ("run_id", models.UUIDField(default=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
