# Generated by Django 5.2.17 on 2026-09-17 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="focus",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dossier",
            name="report_focus",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dossier",
            name="use_fulltext",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ResearchRun",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("stage", models.CharField(max_length=20)),
                ("focus", models.TextField(blank=True)),
                ("status", models.CharField(default="running", max_length=20)),
                ("metrics", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="research.dossier",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
