# Generated by Django 5.2.17 on 2026-09-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0002_dossier_focus_dossier_report_focus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="report_papers",
            field=models.JSONField(default=list),
        ),
    ]
