# Generated by Django 5.2.17 on 2026-09-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0003_dossier_report_papers"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="investigation",
            field=models.JSONField(default=dict),
        ),
    ]
