# Generated by Django 5.2.17 on 2026-09-17 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import research.source_fields


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0004_dossier_investigation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("digest", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UsageBucket",
            fields=[
                ("key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField(db_index=True)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="dossier",
            name="papers",
            field=research.source_fields.SourceJSONField(default=list),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="report_papers",
            field=research.source_fields.SourceJSONField(default=list),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="stage",
            field=models.CharField(
                choices=[
                    ("plan", "Plan"),
                    ("search", "Search"),
                    ("fulltext", "Read PDFs"),
                    ("synthesize", "Synthesize"),
                    ("investigate", "Investigate"),
                ],
                default="plan",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="versions",
            field=research.source_fields.SourceJSONField(default=list),
        ),
        migrations.AddIndex(
            model_name="dossier",
            index=models.Index(fields=["status", "created_at"], name="research_queue_idx"),
        ),
        migrations.AddIndex(
            model_name="dossier",
            index=models.Index(fields=["owner", "-created_at"], name="research_owner_recent_idx"),
        ),
        migrations.AddConstraint(
            model_name="dossier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["draft", "queued", "running", "ready", "failed", "cancelled"])
                ),
                name="research_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="dossier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("stage__in", ["plan", "search", "fulltext", "synthesize", "investigate"])
                ),
                name="research_valid_stage",
            ),
        ),
        migrations.AddConstraint(
            model_name="dossier",
            constraint=models.CheckConstraint(
                condition=models.Q(("limit__gte", 1), ("limit__lte", 20)),
                name="research_valid_limit",
            ),
        ),
        migrations.AddField(
            model_name="sourcesnapshot",
            name="dossier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_snapshots",
                to="research.dossier",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcesnapshot",
            constraint=models.UniqueConstraint(
                fields=("dossier", "digest"), name="research_source_digest_unique"
            ),
        ),
    ]
