# Generated by Django 5.2.17 on 2026-09-17 16:15

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="BenchmarkRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("manifest", models.JSONField(default=dict)),
                ("git_revision", models.CharField(blank=True, max_length=64)),
                ("config", models.JSONField(default=dict)),
                ("metrics", models.JSONField(default=dict)),
                ("environment", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CanonicalPublication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("state", models.CharField(db_index=True, default="active", max_length=20)),
                ("successors", models.JSONField(default=list)),
                ("projection", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("profile", models.JSONField(default=dict)),
                ("status", models.CharField(db_index=True, default="queued", max_length=24)),
                ("cursor", models.JSONField(default=dict)),
                ("counters", models.JSONField(default=dict)),
                ("lease_owner", models.CharField(blank=True, max_length=64)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=128, null=True, unique=True),
                ),
                ("request_hash", models.CharField(blank=True, max_length=64)),
                ("error", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImportFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=512)),
                ("raw", models.JSONField(default=dict)),
                ("code", models.CharField(max_length=64)),
                ("message", models.TextField()),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("retryable", models.BooleanField(default=True)),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="failures",
                        to="records.importrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("external_id", models.CharField(max_length=512)),
                ("doi", models.TextField(blank=True, db_index=True)),
                ("title_key", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="records.canonicalpublication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidatePair",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("state", models.CharField(db_index=True, default="pending", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "left",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="left_pairs",
                        to="records.sourcerecord",
                    ),
                ),
                (
                    "right",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="right_pairs",
                        to="records.sourcerecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceRecordVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("raw", models.JSONField()),
                ("normalized", models.JSONField()),
                ("content_hash", models.CharField(max_length=64)),
                ("normalization_version", models.CharField(default="1", max_length=32)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="records.sourcerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
            },
        ),
        migrations.AddField(
            model_name="sourcerecord",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="records.sourcerecordversion",
            ),
        ),
        migrations.CreateModel(
            name="MatchProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("method", models.CharField(default="lexical-v1", max_length=64)),
                ("config", models.JSONField(default=dict)),
                ("signals", models.JSONField(default=dict)),
                ("warnings", models.JSONField(default=list)),
                ("ranking_score", models.FloatField(null=True)),
                ("recommendation", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposals",
                        to="records.candidatepair",
                    ),
                ),
                (
                    "left_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="records.sourcerecordversion",
                    ),
                ),
                (
                    "right_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="records.sourcerecordversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(max_length=16)),
                ("actor", models.CharField(max_length=150)),
                ("reason", models.TextField(blank=True)),
                ("expected_revision", models.PositiveIntegerField()),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="records.candidatepair",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="records.matchproposal",
                    ),
                ),
                (
                    "withdrawal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawal",
                        to="records.reviewdecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("actor", "idempotency_key"), name="decision_idempotency_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("origin", models.CharField(default="ingest", max_length=64)),
                ("valid_from", models.DateTimeField(auto_now_add=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="records.canonicalpublication",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="records.sourcerecord",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("valid_until__isnull", True)),
                        fields=("record",),
                        name="one_active_membership",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="candidatepair",
            constraint=models.UniqueConstraint(fields=("left", "right"), name="candidate_unique"),
        ),
        migrations.AddConstraint(
            model_name="candidatepair",
            constraint=models.CheckConstraint(
                condition=models.Q(("left__lt", models.F("right"))), name="candidate_ordered"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerecordversion",
            constraint=models.UniqueConstraint(
                fields=("record", "content_hash"), name="source_content_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="sourcerecord",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["title_key"], name="source_title_trgm", opclasses=["gist_trgm_ops"]
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerecord",
            constraint=models.UniqueConstraint(
                fields=("provider", "external_id"), name="source_identity_unique"
            ),
        ),
    ]
